### ISSUE TITLE
Specify the complete destination with `SW_EXPORT_URI`

### ISSUE THREAD

**Issue by leewesleyv** [q-m/scrapy-webarchive#18]
We want to specify the complete destination rather than generating it with `SW_EXPORT_URI` as a prefix.

It would be nice if the invoking system can determine the final filename, otherwise it needs to guess the resulting WACZ filename afterwards. This can help finding the resulting WACZ later, to have a complete filename already.

_Originally posted by @wvengen in https://github.com/q-m/scrapy-webarchive/pull/17#discussion_r1819002662_

**Comment by wvengen** [comment]
Note that there could still be a use-case for providing a path and generating a sensible filename, but I would _also_ like to be able to specify the path to the file.

**Comment by leewesleyv** [comment]
Let's see if we can implement this using the current setting, or if it would be cleaner to introduce an additional setting.

**Comment by wvengen** [comment]
Good point.

**Comment by wvengen** [comment]
Perhaps we can keep it a single setting, where one would normally include variables to generate the filename. That would make the filename also more explicit.

**Comment by leewesleyv** [comment]
Code-wise it would've been a bit cleaner to split up the settings. However, from the perspective of the user it makes more sense to combine the 2 and just define an output location. 

Feature implemented in [a570295](https://github.com/q-m/scrapy-webarchive/commit/a570295cb86b329f41ef9e425705a67c2f1180b8)

**Comment by wvengen** [comment]
Super!

I didn't see this right away in the code (but it must be there), hence the question: how do you know whether the provided setting is a folder, or a full path? I could imagine if it ends with a `/` - in that case it needs to be documented well.
Ah, now I see `isdir` - does that work on object storage too?

I'm ok with not allowing a folder, but always a filename (when the example gives a suitable default, that would be fine - you need to configure it anyway, there is no sensible default for storage location).
