### ISSUE TITLE
Workflow for releasing to PyPI

### ISSUE THREAD

**Issue by leewesleyv** [q-m/scrapy-webarchive#3]
We need to have a workflow for deploying this as a package to PyPI. Come up with a versioning strategy and release workflow.

**Comment by wvengen** [comment]
Let's see if we can use [trusted publishing](https://docs.pypi.org/trusted-publishers/using-a-publisher/).

**Comment by wvengen** [comment]
Registered a pending trusted publisher, workflow name should be `release.yml`, the environment name is `release`.

**Comment by leewesleyv** [comment]
@wvengen Should we also create an account for `test.pypi`?

**Comment by wvengen** [comment]
Done. Registered a pending trusted publisher, workflow name should be `release-test.yml`, the environment name is `release-test`.
