### ISSUE TITLE
Compatibility with Scrapy

### ISSUE THREAD

**Issue by leewesleyv** [q-m/scrapy-webarchive#4]
Currently the version of Scrapy is pinned to `2.11.2` (in `pyproject.toml`). We want to see if we can support a larger range of Scrapy versions.

**Comment by leewesleyv** [comment]
With this we also need to think about the Python versions that we want to/can support.

**Comment by wvengen** [comment]
Ideally, I guess, all officially supported Python versions + any older versions we need to support.
https://www.python.org/downloads/ lists six currently supported minor versions.

**Comment by leewesleyv** [comment]
With Python 3.8 EOL I think we should drop that. But it seems that Scrapy does not officially support Python 3.13 yet, so I would say that we follow whatever Scrapy is doing.

**Comment by leewesleyv** [comment]
Resolved in #13

Will open a new ticket for Python 3.13 support (where we are dependent on Scrapy's official Python 3.13 support).
